CREATE DATABASE Novel_Navigators;

USE Novel_Navigators;

CREATE TABLE Authors (
    author_id INT AUTO_INCREMENT PRIMARY KEY,
    author_name VARCHAR(255) NOT NULL
);

CREATE TABLE Genres (
    genre_id INT AUTO_INCREMENT PRIMARY KEY,
    genre_name VARCHAR(50) NOT NULL
);

CREATE TABLE Books (
    book_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author_id INT,
    genre_id INT,
    FOREIGN KEY (author_id) REFERENCES Authors (author_id),
    FOREIGN KEY (genre_id) REFERENCES Genres (genre_id)
);

CREATE TABLE Reviews (
    review_id INT AUTO_INCREMENT PRIMARY KEY,
    book_id INT,
    message VARCHAR(255),
    FOREIGN KEY (book_id) REFERENCES Books (book_id)
);

INSERT INTO Authors (author_name)
VALUES ('Miguel De Cervantes'),
	   ('John Bunyan'),
       ('Daniel Defoe'),
       ('Jonathan Swift'),
       ('Henry Fielding'),
       ('Samuel Richardson'),
       ('Laurence Sterne'),
       ('Pierre Choderlos de Laclos'),
       ('Jane Austen'),
       ('Mary Shelley'),
       ('Thomas Love Peacock'),
       ('Honoré de Balzac'),
       ('Stendhal'),
       ('Alexandre Dumas'),
       ('Benjamin Disraeli'),
       ('Charles Dickens'),
       ('Emily Brontë'),
       ('Charlotte Brontë'),
       ('William Makepeace Thackeray'),
       ('Nathaniel Hawthorne'),
       ('Herman Melville'),
       ('Gustave Flaubert'),
       ('Wilkie Collins'),
       ('Lewis Carroll'),
       ('Louisa May Alcott'),
       ('Anthony Trollope'),
       ('Leo Tolstoy'),
       ('George Eliot'),
	   ('Fyodor Dostoevsky'),
       ('Henry James'),
       ('Mark Twain'),
       ('Robert Louis Stevenson'),
       ('Jerome K. Jerome'),
       ('Oscar Wilde'),
       ('George Grossmith'),
       ('Thomas Hardy'),
       ('Erskine Childers'),
       ('Jack London'),
       ('Joseph Conrad'),
       ('Kenneth Grahame'),
       ('Marcel Proust'),
       ('D.H. Lawrence'),
       ('Ford Madox Ford'),
       ('John Buchan'),
       ('James Joyce'),
       ('Virginia Woolf'),
       ('E.M. Forster'),
       ('F. Scott Fitzgerald'),
       ('Franz Kafka'),
       ('Ernest Hemingway'),
       ('Louis-Ferdinand Céline'),
       ('William Faulkner'),
       ('Aldous Huxley'),
       ('Evelyn Waugh'),
       ('John Dos Passos'),
       ('Raymond Chandler'),
       ('Nancy Mitford'),
       ('Albert Camus'),
       ('George Orwell'),
       ('Samuel Beckett'),
       ('J.D. Salinger'),
       ('Flannery O\'Connor'),
       ('E.B. White'),
       ('J.R.R. Tolkien'),
	   ('Kingsley Amis'),
       ('William Golding'),
       ('Graham Greene'),
       ('Jack Kerouac'),
       ('Vladimir Nabokov'),
       ('Günter Grass'),
       ('Chinua Achebe'),
       ('Muriel Spark'),
       ('Harper Lee'),
       ('Joseph Heller'),
       ('Saul Bellow'),
       ('Gabriel García Márquez'),
       ('Elizabeth Taylor'),
       ('John le Carré'),
       ('Toni Morrison'),
       ('Beryl Bainbridge'),
       ('Norman Mailer'),
       ('Italo Calvino'),
       ('V.S. Naipaul'),
       ('J. M. Coetzee'),
       ('Marilynne Robinson'),
       ('Alasdair Gray'),
       ('Paul Auster'),
       ('Roald Dahl'),
       ('Primo Levi'),
       ('Martin Amis'),
       ('Kazuo Ishiguro'),
       ('Peter Carey'),
       ('Milan Kundera'),
       ('Salman Rushdie'),
       ('James Ellroy'),
       ('Angela Carter'),
       ('Ian McEwan'),
       ('Philip Pullman'),
       ('Philip Roth'),
       ('W.G. Sebald'),
       ('Stephen King'),
       ('J.K. Rowling'),
       ('Haruki Murakami'),
       ('Agatha Christie'),
       ('Leo Tolstoy'),
       ('Fyodor Dostoevsky');


INSERT INTO Genres (genre_name)
VALUES ('Comedy'),
	   ('Romance'),
       ('Fantasy/SciFi'),
       ('Action/Adventure'),
       ('Mystery/Horror'),
       ('Crime/Detective'),
       ('Drama'),
       ('Childrens'),
       ('Philosophical/Religious'),
       ('Historical'),
       ('Fiction'),
       ('NonFiction');


INSERT INTO Books (title, author_id, genre_id)
VALUES ('Don Quixote', 1, 4),
	   ('Pilgrim\'s Progress', 2, 9),
       ('Robinson Crusoe', 3, 4),
       ('Gulliver\'s Travels', 4, 4),
       ('Tom Jones', 5, 1),
       ('Clarissa', 6, 2),
       ('Tristram Shandy', 7, 1),
       ('Dangerous Liaisons', 8, 2),
       ('Emma', 9, 2),
       ('Frankenstein', 10, 5),
       ('Nightmare Abbey', 11, 5),
       ('The Black Sheep', 12, 10),
       ('The Charterhouse of Parma', 13, 10),
       ('The Count of Monte Cristo', 14, 4),
       ('Sybil', 15, 10),
       ('David Copperfield', 16, 10),
       ('Wuthering Heights', 17, 2),
       ('Jane Eyre', 18, 2),
       ('Vanity Fair', 19, 2),
       ('The Scarlet Letter', 20, 10),
       ('Moby-Dick', 21, 4),
       ('Madame Bovary', 22, 2),
       ('The Woman in White', 23, 5),
       ('Alice\'s Adventures In Wonderland', 24, 3),
       ('Little Women', 25, 2),
       ('The Way We Live Now', 26, 10),
       ('Anna Karenina', 27, 2),
       ('Daniel Deronda', 28, 2),
	   ('The Brothers Karamazov', 29, 9),
       ('The Portrait of a Lady', 30, 2),
       ('The Adventures of Huckleberry Finn', 31, 4),
       ('The Strange Case of Dr. Jekyll and Mr. Hyde', 32, 3),
       ('Three Men in a Boat', 33, 1),
       ('The Picture of Dorian Gray', 34, 5),
       ('The Diary of a Nobody', 35, 1),
       ('Jude the Obscure', 36, 11),
       ('The Riddle of the Sands', 37, 5),
       ('The Call of the Wild', 38, 4),
       ('Nostromo', 39, 10),
       ('The Wind in the Willows', 40, 8),
       ('In Search of Lost Time', 41, 9),
       ('The Rainbow', 42, 2),
       ('The Good Soldier', 43, 10),
       ('The Thirty-Nine Steps', 44, 5),
       ('Ulysses', 45, 11),
       ('Mrs. Dalloway', 46, 10),
       ('A Passage to India', 47, 10),
       ('The Great Gatsby', 48, 2),
       ('The Trial', 49, 9),
       ('Men Without Women', 50, 11),
       ('Journey to the End of the Night', 51, 9),
       ('As I Lay Dying', 52, 11),
       ('Brave New World', 53, 3),
       ('Scoop', 54, 1),
       ('USA', 55, 11),
       ('The Big Sleep', 56, 5),
       ('The Pursuit of Love', 57, 2),
       ('The Plague', 58, 9),
       ('Nineteen Eighty-Four', 59, 3),
       ('Malone Dies', 60, 11),
       ('The Catcher in the Rye', 61, 11),
       ('Wise Blood', 62, 11),
       ('Charlotte’s Web', 63, 8),
       ('The Lord of the Rings', 64, 3),
	   ('Lucky Jim', 65, 1),
       ('Lord of the Flies', 66, 3),
       ('The Quiet American', 67, 11),
       ('On the Road', 68, 11),
       ('Lolita', 69, 11),
       ('The Tin Drum', 70, 10),
       ('Things Fall Apart', 71, 10),
       ('The Prime of Miss Jean Brodie', 72, 10),
       ('To Kill a Mockingbird', 73, 10),
       ('Catch-22', 74, 11),
       ('Herzog', 75, 11),
       ('One Hundred Years of Solitude', 76, 11),
       ('Mrs. Palfrey at the Claremont', 77, 11),
       ('Tinker, Tailor, Soldier, Spy', 78, 5),
       ('Song of Solomon', 79, 11),
       ('The Bottle Factory Outing', 80, 1),
       ('The Executioner\'s Song', 81, 6),
       ('If on a Winter\'s Night a Traveller', 82, 11),
       ('A Bend in the River', 83, 10),
       ('Waiting for the Barbarians', 84, 10),
       ('Housekeeping', 85, 11),
       ('Lanark', 86, 3),
       ('The New York Trilogy', 87, 5),
       ('The BFG', 88, 8),
       ('The Periodic Table', 89, 12),
       ('Money', 90, 11),
       ('An Artist of the Floating World', 91, 10),
       ('Oscar and Lucinda', 92, 2),
       ('The Book of Laughter and Forgetting', 93, 9),
       ('Haroun and the Sea of Stories', 94, 3),
       ('L.A. Confidential', 95, 6),
       ('Wise Children', 96, 11),
       ('Atonement', 97, 2),
       ('Northern Lights', 98, 3),
       ('American Pastoral', 99, 11),
       ('Austerlitz', 100, 10),
       ('The Shining', 101, 5),
       ('Harry Potter and the Philosopher''s Stone', 102, 3),
       ('Norwegian Wood', 103, 3),
       ('Murder on the Orient Express', 104, 6),
       ('Emma', 9, 2),
       ('Anna Karenina', 105, 2),
       ('Crime and Punishment', 106, 7);
  
  
INSERT INTO Reviews (book_id, message)
VALUES 	(1, 'A knight in tinfoil armor jousts with windmills. More delusions per page than a politician''s memoir.'),
		(2, 'Christian''s journey: more detours than Google Maps. Beware of allegorical traffic jams and literal pitfalls.'),
		(3, 'Crusoe''s guide to island living: Talk to your parrot, avoid cannibals, and never forget to make friends with a volleyball.'),
		(4, 'Swift''s guide to world travel: Expect giants, tiny folk, and a horse''s opinion. Perfect for readers who prefer their adventures with a side of satire.'),
		(5, 'Follow Tom''s romps and mishaps through 18th-century England. It''s like a soap opera, but with more wigs and less melodrama.'),
		(6, 'Richardson''s epistolary epic: 1500 pages of 18th-century drama. Think "Gossip Girl" meets quill pens and corsets.'),
		(7, 'A maze of digressions, footnotes, and questionable anecdotes. Reading it is like being lost in a library after hours.'),
		(8, 'Intrigue, seduction, and wigs aplenty. Imagine "Gossip Girl," but set in pre-revolutionary France, and everyone''s a scheming aristocrat.'),
		(9, 'Austen''s matchmaking misadventures: More misunderstandings than a game of telephone. Jane Austen proves that meddling in love always leads to comedy.'),
		(10, 'When playing god goes wrong. It''s like "The Bachelor," but with lightning and fewer roses.'),
		(11, 'Gothic gloom meets social satire. It''s like a dinner party with Edgar Allan Poe and Oscar Wilde as guests.'),
		(12, 'Trollope''s tale of family feuds and forbidden love. More scandalous than a tabloid headline!'),
		(13, 'Stendhal''s epic of love, war, and Italian intrigue. Like "Game of Thrones," but with fewer dragons and more courtly drama.'),
		(14, 'Revenge is a dish best served with a side of swashbuckling. Dumas delivers justice, betrayal, and a treasure trove of drama.'),
		(15, 'Disguises, deception, and class struggle in Victorian England. Think "Downton Abbey" with more riots and fewer servants.'),
		(16, 'Orphaned, oppressed, but never out of hope. More twists than a Dickensian plot twist!'),
		(17, 'Brontë''s brooding masterpiece: Love, loss, and the Yorkshire moors. Prepare for stormy weather and even stormier emotions.'),
		(18, 'Brontë''s classic tale of love, mystery, and madwomen in attics. Mr. Rochester''s secrets are juicier than Jane''s afternoon tea.'),
		(19, 'More scandalous than a reality TV reunion show. Keep your wits sharp and your bonnet on tight!'),
		(20, 'Adultery, guilt, and a red-hot fashion statement. It''s like "Mean Girls," but in colonial America.'),
		(21, 'Ahab''s obsession with a certain white whale makes "finding Nemo" look like child''s play. Grab your harpoons and prepare for literary depths.'),
		(22, 'More affairs than a French soap opera, but with better prose.'),
		(23, 'Ghosts, secrets, and a mysterious woman in, you guessed it, white. Prepare for twists as sharp as a corset''s boning!'),
		(24, 'Talking rabbits, disappearing cats, and tea parties gone mad. It''s like "Fantasia" on literary steroids!'),
		(25, 'Louisa May Alcott''s heartwarming tale of sisterhood and struggle. More wholesome than a batch of freshly baked cookies.'),
		(26, 'Corruption, scandal, and gossip in Victorian England. It''s like "Gossip Girl" for the upper crust.'),
		(27, 'Tolstoy''s epic of love, betrayal, and Russian aristocracy. More melodrama than a soap opera marathon.'),
		(28, 'Eliot''s exploration of love and identity. Secrets, society, and a search for self in Victorian England. Cue the period drama music!'),
		(29, 'Murder, madness, and metaphysical musings. Prepare for existential crises aplenty!'),
		(30, 'More artful deception than a con artist''s masterpiece.'),
		(31, 'Twain''s river journey with Huck and Jim: More escapades than a carnival funhouse. Get ready for laughs and life lessons on the Mississippi.'),
		(32, 'Double trouble with a side of moral quandary. Hide your potions, folks!'),
		(33, 'Jerome K. Jerome''s comedic river romp. More misadventures than a sitcom marathon. Pack your oars and leave sanity at the dock!'),
		(34, 'Wilde''s portrait of vanity and vice. More debauchery than a rockstar''s tour bus. Beauty, corruption, and a touch of the supernatural.'),
		(35, 'Grossmith''s comedic masterpiece. More everyday absurdities than a reality TV show.'),
		(36, 'Hardy''s tragic tale of dreams dashed. More misery than a rainy day in a graveyard. Grab your tissues and brace for heartache.'),
		(37, 'More intrigue than a Cold War novel. Keep your wits sharp and your sandcastle defenses up!'),
		(38, 'More canine courage than a pack of wolves. Join Buck on a journey from domestication to domination.'),
		(39, 'More treachery than a pirate''s code. Set sail for the heart of darkness in Latin America.'),
		(40, 'More tea parties than a teddy bear picnic. Join Mole, Rat, and friends for riverside antics!'),
		(41, 'More recollections than a family reunion slideshow. Get lost in the labyrinth of remembrance.'),
		(42, 'More passion than a soap opera, but with better writing.'),
		(43, 'More twists than a pretzel factory. Trust no one in this web of lies.'),
		(44, 'More thrills than a rollercoaster ride. Keep your wits about you and your passport handy!'),
		(45, 'More puzzles than a crossword convention. Dive into the stream of consciousness and try not to drown.'),
		(46, 'More introspection than a therapy session. Step into Clarissa Dalloway''s shoes and explore the depths of her mind.'),
		(47, 'More cultural clashes than a United Nations summit. Navigate the complexities of empire and identity.'),
		(48, 'More parties than a rockstar''s tour bus. Join Gatsby and company for a soirée to remember.'),
		(49, 'More absurdity than a Monty Python sketch. Enter the labyrinth of guilt and innocence.'),
		(50, 'More brooding than a stormy night at sea. Dive into the depths of masculinity.'),
		(51, 'More despair than a funeral dirge. Follow Bardamu on a journey to the heart of darkness.'),
		(52, 'More dysfunctional family drama than a reality TV show. Strap in for a wild ride through Mississippi.'),
		(53, 'More chilling than an iceberg. Enter a world where pleasure reigns supreme and humanity is on the brink.'),
		(54, 'More absurdity than a newsroom on election night. Hold onto your press pass and prepare for laughs.'),
		(55, 'More characters than a Dickens novel. Get swept up in the tide of history.'),
		(56, 'More twists than a pretzel factory. Enter the seedy underbelly of LA with Philip Marlowe.'),
		(57, 'More romantic mishaps than a rom-com marathon. Hold onto your hat and prepare for laughs.'),
		(58, 'More existential angst than a philosophy lecture. Confront the absurdity of life in the face of death.'),
		(59, 'More chilling than a polar vortex. Enter a world of surveillance and thoughtcrime.'),
		(60, 'More absurdity than a clown convention. Follow Malone on his journey to the end.'),
		(61, 'More rebellion than a punk concert. Join Holden Caulfield on a journey through the phoniness of adulthood.'),
		(62, 'More religious satire than a Sunday sermon. Brace yourself for a darkly comic exploration of faith and fanaticism.'),
		(63, 'More heartwarming than a hug from your favorite pet. Join Wilbur and Charlotte on a web of love.'),
		(64, 'More quests than a video game. Enter Middle-earth and prepare for an adventure of epic proportions.'),
		(65, 'More mishaps than a sitcom marathon. Join Jim Dixon on a hilarious journey through the absurdities of university life.'),
		(66, 'More chaos than a riot. Enter the jungle and confront the darkness within.'),
		(67, 'More intrigue than a spy thriller. Navigate the complexities of war and morality.'),
		(68, 'More wanderlust than a travel blog. Hit the road with Sal and Dean for a journey of self-discovery.'),
		(69, 'More taboo than a scandalous affair. Enter Humbert Humbert''s twisted world of obsession and desire.'),
		(70, 'More surreal than a Dali painting. Follow Oskar on a journey through the madness of history.'),
		(71, 'More tragedy than a Shakespearean play. Witness the rise and fall of Okonkwo in colonial Nigeria.'),
		(72, 'More manipulation than a political campaign. Join Miss Brodie''s set for lessons in life and love.'),
		(73, 'More courtroom drama than a legal thriller. Join Scout and Atticus for a lesson in justice and compassion.'),
		(74, 'More absurdity than a clown convention. Enter the mad world of Yossarian and the paradoxes of war.'),
		(75, 'More introspection than a therapy session. Join Moses Herzog on a journey through the complexities of life.'),
		(76, 'More miracles than a saint''s hagiography. Enter the enchanting world of the Buendía family.'),
		(77, 'More heartwarming than a hug from a grandparent. Join Mrs. Palfrey for tea and sympathy.'),
		(78, 'More intrigue than a spy novel. Join George Smiley on a hunt for the mole in British intelligence.'),
		(79, 'More poetry than a sonnet. Follow Milkman Dead on a journey through African-American history.'),
		(80, 'More mischief than a factory full of monkeys. Join Freda and Brenda for a day of chaos and calamity.'),
		(81, 'More gripping than a courtroom drama. Dive into the dark heart of America''s criminal justice system.'),
		(82, 'More metafictional twists than a Möbius strip. Join the reader on a journey through the mysteries of storytelling.'),
		(83, 'More cultural clashes than a UN summit. Navigate the murky waters of identity and politics.'),
		(84, 'More chilling than an Arctic winter. Confront the darkness of human nature.'),
		(85, 'More haunting than a ghost story. Enter the world of Ruth and Lucille for a lesson in resilience.'),
		(86, 'More mind-bending than a psychedelic trip. Explore the depths of imagination and despair.'),
		(87, 'More mysteries than a Sherlock Holmes novel. Enter the labyrinth of the city and the self.'),
		(88, 'More magical than a fairy tale. Join Sophie and the Big Friendly Giant for an adventure of gigantic proportions.'),
		(89, 'More elements than a periodic table. Enter the laboratory of life and witness the alchemy of memory.'),
		(90, 'More debauchery than a Wall Street banker''s bonus party. Follow John Self on a journey through the underbelly of capitalism.'),
		(91, 'More introspection than a Zen meditation. Join Masuji Ono on a journey through the complexities of memory.'),
		(92, 'More passion than a bushfire. Join Oscar and Lucinda on a journey across the Outback.'),
		(93, 'More existential musings than a coffeehouse conversation. Enter the world of laughter and oblivion.'),
		(94, 'More magic than a genie''s lamp. Join Haroun on a journey through the power of imagination.'),
		(95, 'More twists than a Hollywood plot. Enter the seedy underbelly of Los Angeles and confront the darkness within.'),
		(96, 'More drama than a Broadway musical. Join the Chance sisters for a whirlwind tour of fame and fortune.'),
		(97, 'More heartache than a breakup ballad. Enter the world of Briony Tallis for a journey through love and loss.'),
		(98, 'More magic than a wizard''s wand. Join Lyra on a journey to the frozen north and beyond.'),
		(99, 'More tragedy than a Greek epic. Follow Seymour "Swede" Levov on a journey through the upheavals of the 20th century.'),
		(100, 'More melancholy than a rainy day. Enter the world of Jacques Austerlitz for a journey through the shadows of history.'),
		(101, 'More scares than a haunted house. Enter the Overlook Hotel and confront your deepest fears.'),
		(102, 'More spells than a wizarding duel. Join Harry, Hermione, and Ron on a journey to Hogwarts School of Witchcraft and Wizardry.'),
		(103, 'More heartache than a breakup ballad. Join Toru Watanabe on a journey through the complexities of love and memory.'),
		(104, 'More suspects than a lineup at Scotland Yard. Join Hercule Poirot on a journey through intrigue and deception.'),
		(105, 'More matchmaking than a dating app. Join Emma Woodhouse on a journey through the pitfalls of love and social etiquette.'),
		(106, 'More passion than a soap opera. Follow Anna on a journey through the glittering salons and snowy landscapes of Imperial Russia.'),
		(107, 'More guilt than a confession booth. Follow Raskolnikov on a journey through the depths of the human soul.');
